#!/usr/bin/env sh

# Source Husky
. "$(dirname -- "$0")/_/husky.sh"

# Run lint check and format check
npm run prepush

# Check the exit code of the previous command
if [ $? -ne 0 ]; then
  echo "There was an error in the linting or formatting. Push aborted."
  exit 1  # Exit with a non-zero status code to stop the push
fi
